---
name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: java version
        run: java -version
      - name: Debug
        run: ./gradlew checkDockerClient --info --stacktrace
        timeout-minutes: 10
      - name: Check
        run: ./gradlew check --info --stacktrace
        timeout-minutes: 10
